### ISSUE TITLE
Column 可能會混淆

### ISSUE THREAD

**Issue by excusezmoi** [dobahsi/dobahsi.github.io#8]
HTML中
        <div class="main-nav">
            <a href="#">
                關於學會
            </a>
            <a href="#">
                活動公告
            </a>
            <a href="#">
                學會出版
            </a>
            <a href="#">
                網路資源
            </a>
        </div>
的部分，在銀幕變大的時候(例如用電腦)，會變成四個Column。可能有VJ之前說Column有時候有階層關係(最新消息、最新活動)，有時候沒有(此處)的問題。

**Comment by dobahsi** [comment]
那該直接改成一行就一個按鈕嗎 然後持續這四個

**Comment by excusezmoi** [comment]
好啊 感覺不錯
